In [1]:
import numpy as np
import pandas as pd

In [2]:
r_cols=['user_id','movie_id','rating','unix_timestamp']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols,encoding='latin-1')

In [3]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [4]:
n_users=ratings.user_id.unique().shape[0]
n_items=ratings.movie_id.unique().shape[0]

In [5]:
print("The no of users:",n_users)
print("The no of items:",n_items)

The no of users: 943
The no of items: 1682

In [6]:
datama=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')

In [7]:
datama

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data_matrix=datama.replace(np.nan,0)

In [9]:
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(data_matrix,metric='cosine')
item_similarity=pairwise_distances(data_matrix.T,metric='cosine')

In [11]:
user_similarity

array([[1.33226763e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 0.00000000e+00, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 0.00000000e+00, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

In [12]:
item_similarity

array([[2.22044605e-16, 5.97617822e-01, 6.69755213e-01, ...,
        1.00000000e+00, 9.52816933e-01, 9.52816933e-01],
       [5.97617822e-01, 2.22044605e-16, 7.26930825e-01, ...,
        1.00000000e+00, 9.21700637e-01, 9.21700637e-01],
       [6.69755213e-01, 7.26930825e-01, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 9.03124947e-01],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [9.52816933e-01, 9.21700637e-01, 9.03124947e-01, ...,
        1.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [13]:
import numpy as np

def predict(ratings, similarity, type='user'):
    if type == 'user':
        # User-based prediction
        mean_user_rating = ratings.mean(axis=1)
        ratings_diff = ratings - mean_user_rating[:, np.newaxis]
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.abs(similarity).sum(axis=1)[:, np.newaxis]
    
    elif type == 'item':
        # Item-based prediction
        pred = ratings.dot(similarity.T) / np.abs(similarity).sum(axis=1)

    return pred

In [14]:
# Example Data
num_users = 943
num_items = 1682

# Random ratings matrix (users x items)
data_matrix = np.random.rand(num_users, num_items)

# User similarity matrix (users x users)
user_similarity = np.random.rand(num_users, num_users)

# Item similarity matrix (items x items)
item_similarity = np.random.rand(num_items, num_items)

# Predict user-based and item-based scores
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, item_similarity, type='item')

print("User-based Prediction Shape:", user_prediction.shape)
print("Item-based Prediction Shape:", item_prediction.shape)

User-based Prediction Shape: (943, 1682)
Item-based Prediction Shape: (943, 1682)

In [15]:
user_prediction

array([[0.5111065 , 0.49765992, 0.49488746, ..., 0.50865973, 0.50440335,
        0.48080416],
       [0.50502932, 0.50809236, 0.493517  , ..., 0.50572087, 0.50248746,
        0.48684811],
       [0.50668302, 0.50262138, 0.48910891, ..., 0.51058109, 0.49931093,
        0.4828553 ],
       ...,
       [0.5090588 , 0.49865967, 0.49626912, ..., 0.51295046, 0.51565319,
        0.48878558],
       [0.5189022 , 0.49596209, 0.52256872, ..., 0.52343626, 0.52294685,
        0.50627285],
       [0.50043894, 0.49862033, 0.50020868, ..., 0.50800514, 0.50531957,
        0.48635189]])

In [16]:
input_user=34

In [17]:
user_sim_table=pd.DataFrame(user_similarity)

In [18]:
user_sim_table

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,0.334615,0.827516,0.673424,0.950128,0.377282,0.345908,0.594070,0.242773,0.964047,0.488433,...,0.950698,0.214771,0.582839,0.584101,0.988659,0.420594,0.744359,0.673124,0.006203,0.613944
1,0.310350,0.132251,0.685628,0.855234,0.377726,0.618142,0.379232,0.718915,0.082657,0.272374,...,0.893769,0.829883,0.891532,0.656205,0.693511,0.076320,0.977490,0.919767,0.938608,0.635078
2,0.520704,0.181231,0.333656,0.318565,0.236301,0.127561,0.818650,0.978535,0.546225,0.607109,...,0.702071,0.031880,0.308319,0.173911,0.975922,0.296501,0.505705,0.433777,0.520271,0.748582
3,0.515363,0.492360,0.718730,0.671549,0.507886,0.748252,0.408424,0.003919,0.120587,0.870913,...,0.738850,0.275677,0.891645,0.179415,0.178495,0.237218,0.565844,0.926808,0.122006,0.465142
4,0.086337,0.434535,0.775419,0.338145,0.414511,0.140668,0.206774,0.264528,0.614147,0.630118,...,0.091024,0.218437,0.520796,0.286340,0.740705,0.418863,0.619611,0.829114,0.861481,0.242411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.106909,0.346179,0.711046,0.061967,0.228852,0.263096,0.942990,0.377228,0.456836,0.490133,...,0.355294,0.635804,0.122804,0.436803,0.718701,0.716241,0.815928,0.149205,0.698605,0.793059
939,0.937054,0.568134,0.187335,0.914065,0.827792,0.951487,0.696432,0.383391,0.441272,0.624044,...,0.857146,0.667678,0.786383,0.671479,0.888062,0.157901,0.957076,0.729562,0.705947,0.530861
940,0.821712,0.020355,0.374728,0.831039,0.806048,0.928598,0.560168,0.823516,0.851988,0.038685,...,0.862236,0.778647,0.005336,0.977287,0.089185,0.386071,0.313936,0.680580,0.990456,0.550424
941,0.382124,0.376736,0.075038,0.988692,0.820937,0.037640,0.900685,0.469677,0.000748,0.158192,...,0.625799,0.508612,0.888369,0.821774,0.289169,0.540874,0.852371,0.106842,0.967618,0.385638
942,0.871760,0.876588,0.990802,0.115846,0.530697,0.078036,0.433251,0.256772,0.184755,0.440069,...,0.451690,0.952401,0.011345,0.035097,0.843636,0.467094,0.354432,0.550692,0.623263,0.278473

In [19]:
similar_input_user=user_sim_table[input_user].sort_values(ascending=True).head(5).index

In [20]:
similar_input_user

Int64Index([695, 827, 549, 799, 548], dtype='int64')

In [21]:
similar_user_input=list(similar_input_user)

In [22]:
similar__user_movieid_list=[]
for sim_user in similar_user_input:
    sim=list(ratings[ratings['user_id']==sim_user]['movie_id'])
    similar__user_movieid_list.append(sim)

In [23]:
len(similar__user_movieid_list)

5

In [24]:
similar__user_movieid_list

[[300,
  307,
  882,
  338,
  301,
  319,
  313,
  260,
  1024,
  995,
  346,
  270,
  311,
  288,
  305,
  242,
  991,
  682,
  895,
  268,
  903,
  354,
  323,
  324,
  264,
  328,
  748,
  289,
  887,
  312,
  333,
  302,
  678,
  286,
  343,
  358,
  989,
  340],
 [329,
  347,
  258,
  268,
  313,
  331,
  272,
  690,
  750,
  301,
  689,
  302,
  269,
  245,
  294,
  288,
  316,
  748,
  289,
  300,
  938,
  332,
  312,
  326,
  343,
  286,
  358,
  333],
 [866,
  50,
  252,
  288,
  225,
  678,
  1047,
  515,
  472,
  100,
  127,
  118,
  411,
  620,
  237,
  181,
  1,
  121,
  748,
  282,
  24,
  323,
  258,
  151,
  405],
 [479,
  45,
  50,
  499,
  258,
  654,
  690,
  319,
  484,
  173,
  174,
  289,
  748,
  286,
  292,
  427,
  127,
  331,
  321,
  307,
  191,
  1545,
  306,
  1063],
 [273,
  690,
  636,
  276,
  322,
  264,
  248,
  1051,
  118,
  887,
  458,
  311,
  255,
  147,
  1405,
  1073,
  657,
  235,
  477,
  760,
  619,
  222,
  298,
  323,
  649,
  281,
  258,
  31,
  270,
  991,
  603,
  307,
  504,
  345,
  315,
  327,
  7,
  12,
  117,
  532,
  23,
  302,
  654,
  121,
  14,
  443,
  333,
  1025,
  460,
  39,
  234,
  1014,
  1278,
  717,
  292,
  928,
  313,
  591,
  1089,
  340,
  344,
  284,
  1016,
  466,
  100,
  282,
  748,
  237,
  185,
  882,
  581,
  642,
  1244,
  283,
  3,
  326,
  245,
  331,
  925,
  678,
  1013,
  751,
  295,
  229,
  905,
  277,
  898,
  358,
  13,
  156,
  595,
  343,
  346,
  257,
  203,
  79,
  525,
  628,
  310,
  742,
  226,
  181,
  56,
  696,
  978,
  17,
  55,
  286,
  1011,
  305,
  233,
  762,
  50,
  950,
  15,
  659,
  370,
  546,
  316,
  300,
  275,
  254,
  347,
  472,
  750,
  291,
  539,
  597,
  250,
  431,
  271,
  515,
  252,
  9,
  405,
  683,
  98,
  293,
  127,
  1,
  164,
  272,
  1047,
  294,
  471,
  413,
  176,
  328,
  924,
  151,
  288,
  475,
  183,
  218,
  25]]

In [25]:
import itertools
similar__user_movieid_single_list=list(itertools.chain.from_iterable(similar__user_movieid_list))

In [26]:
len(similar__user_movieid_single_list)

270

In [27]:
unique_movieid_similar_user=set(similar__user_movieid_single_list)

In [28]:
len(unique_movieid_similar_user)

193

In [29]:
input_user_watched_movieid=list(ratings[ratings['user_id']==input_user]['movie_id'].values)

In [30]:
input_user_watched_movieid

[312,
 242,
 690,
 310,
 259,
 299,
 245,
 332,
 329,
 286,
 1024,
 324,
 294,
 292,
 990,
 289,
 898,
 899,
 288,
 991]

In [31]:
recom=[]
for per_id in unique_movieid_similar_user:
    if(per_id in input_user_watched_movieid):
        pass
    else:
        recom.append(per_id)

In [32]:
len(recom)

177

In [33]:
sorted(recom)

[1,
 3,
 7,
 9,
 12,
 13,
 14,
 15,
 17,
 23,
 24,
 25,
 31,
 39,
 45,
 50,
 55,
 56,
 79,
 98,
 100,
 117,
 118,
 121,
 127,
 147,
 151,
 156,
 164,
 173,
 174,
 176,
 181,
 183,
 185,
 191,
 203,
 218,
 222,
 225,
 226,
 229,
 233,
 234,
 235,
 237,
 248,
 250,
 252,
 254,
 255,
 257,
 258,
 260,
 264,
 268,
 269,
 270,
 271,
 272,
 273,
 275,
 276,
 277,
 281,
 282,
 283,
 284,
 291,
 293,
 295,
 298,
 300,
 301,
 302,
 305,
 306,
 307,
 311,
 313,
 315,
 316,
 319,
 321,
 322,
 323,
 326,
 327,
 328,
 331,
 333,
 338,
 340,
 343,
 344,
 345,
 346,
 347,
 354,
 358,
 370,
 405,
 411,
 413,
 427,
 431,
 443,
 458,
 460,
 466,
 471,
 472,
 475,
 477,
 479,
 484,
 499,
 504,
 515,
 525,
 532,
 539,
 546,
 581,
 591,
 595,
 597,
 603,
 619,
 620,
 628,
 636,
 642,
 649,
 654,
 657,
 659,
 678,
 682,
 683,
 689,
 696,
 717,
 742,
 748,
 750,
 751,
 760,
 762,
 866,
 882,
 887,
 895,
 903,
 905,
 924,
 925,
 928,
 938,
 950,
 978,
 989,
 995,
 1011,
 1013,
 1014,
 1016,
 1025,
 1047,
 1051,
 1063,
 1073,
 1089,
 1244,
 1278,
 1405,
 1545]

In [34]:
sorted(unique_movieid_similar_user)

[1,
 3,
 7,
 9,
 12,
 13,
 14,
 15,
 17,
 23,
 24,
 25,
 31,
 39,
 45,
 50,
 55,
 56,
 79,
 98,
 100,
 117,
 118,
 121,
 127,
 147,
 151,
 156,
 164,
 173,
 174,
 176,
 181,
 183,
 185,
 191,
 203,
 218,
 222,
 225,
 226,
 229,
 233,
 234,
 235,
 237,
 242,
 245,
 248,
 250,
 252,
 254,
 255,
 257,
 258,
 260,
 264,
 268,
 269,
 270,
 271,
 272,
 273,
 275,
 276,
 277,
 281,
 282,
 283,
 284,
 286,
 288,
 289,
 291,
 292,
 293,
 294,
 295,
 298,
 300,
 301,
 302,
 305,
 306,
 307,
 310,
 311,
 312,
 313,
 315,
 316,
 319,
 321,
 322,
 323,
 324,
 326,
 327,
 328,
 329,
 331,
 332,
 333,
 338,
 340,
 343,
 344,
 345,
 346,
 347,
 354,
 358,
 370,
 405,
 411,
 413,
 427,
 431,
 443,
 458,
 460,
 466,
 471,
 472,
 475,
 477,
 479,
 484,
 499,
 504,
 515,
 525,
 532,
 539,
 546,
 581,
 591,
 595,
 597,
 603,
 619,
 620,
 628,
 636,
 642,
 649,
 654,
 657,
 659,
 678,
 682,
 683,
 689,
 690,
 696,
 717,
 742,
 748,
 750,
 751,
 760,
 762,
 866,
 882,
 887,
 895,
 898,
 903,
 905,
 924,
 925,
 928,
 938,
 950,
 978,
 989,
 991,
 995,
 1011,
 1013,
 1014,
 1016,
 1024,
 1025,
 1047,
 1051,
 1063,
 1073,
 1089,
 1244,
 1278,
 1405,
 1545]

In [35]:
sorted(input_user_watched_movieid)

[242,
 245,
 259,
 286,
 288,
 289,
 292,
 294,
 299,
 310,
 312,
 324,
 329,
 332,
 690,
 898,
 899,
 990,
 991,
 1024]

In [36]:
list(set(unique_movieid_similar_user)&set(input_user_watched_movieid))

[1024,
 289,
 898,
 288,
 292,
 324,
 294,
 329,
 332,
 690,
 242,
 245,
 310,
 312,
 286,
 991]

In [37]:
user_pred=pd.DataFrame(user_prediction)

In [38]:
user_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.511107,0.497660,0.494887,0.483699,0.475283,0.495466,0.486355,0.489325,0.513064,0.507560,...,0.493139,0.476785,0.505948,0.492859,0.492782,0.490189,0.494718,0.508660,0.504403,0.480804
1,0.505029,0.508092,0.493517,0.493694,0.473498,0.500029,0.497475,0.486825,0.524123,0.500812,...,0.507526,0.476905,0.515418,0.493636,0.500591,0.494464,0.503851,0.505721,0.502487,0.486848
2,0.506683,0.502621,0.489109,0.484843,0.475315,0.493175,0.502128,0.493600,0.513868,0.503202,...,0.487659,0.472895,0.499189,0.500244,0.490068,0.485565,0.491182,0.510581,0.499311,0.482855
3,0.499537,0.511139,0.505441,0.490301,0.481674,0.493691,0.492274,0.480349,0.514988,0.498647,...,0.498867,0.486328,0.506170,0.495226,0.497546,0.498071,0.503051,0.502481,0.505996,0.497837
4,0.512564,0.512052,0.505573,0.483299,0.478649,0.485458,0.490504,0.491869,0.512104,0.498773,...,0.503870,0.477531,0.513671,0.497552,0.509727,0.503195,0.493338,0.517850,0.515986,0.488575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.490908,0.487932,0.486803,0.479274,0.479178,0.480981,0.499103,0.478037,0.510205,0.490700,...,0.492963,0.468666,0.495349,0.493234,0.492556,0.493319,0.499566,0.503537,0.502910,0.486507
939,0.499815,0.491197,0.496413,0.491615,0.469451,0.501654,0.498866,0.483954,0.509719,0.497401,...,0.504848,0.475337,0.507145,0.499736,0.492280,0.500058,0.491295,0.504967,0.496247,0.487598
940,0.509059,0.498660,0.496269,0.476385,0.485311,0.495591,0.494025,0.490122,0.507512,0.504696,...,0.504285,0.492621,0.509662,0.510610,0.492228,0.502607,0.498138,0.512950,0.515653,0.488786
941,0.518902,0.495962,0.522569,0.499484,0.486197,0.499665,0.497529,0.494098,0.524412,0.514078,...,0.518039,0.498583,0.525875,0.520927,0.503236,0.517716,0.517042,0.523436,0.522947,0.506273
942,0.500439,0.498620,0.500209,0.483884,0.474825,0.497240,0.496790,0.488001,0.514180,0.494842,...,0.497707,0.470539,0.509899,0.504366,0.508152,0.507891,0.492145,0.508005,0.505320,0.486352

In [39]:
user_pred_Trans=user_pred.T

In [40]:
user_pred_Trans

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,0.511107,0.505029,0.506683,0.499537,0.512564,0.514586,0.520122,0.492853,0.495442,0.500648,...,0.503560,0.514525,0.499130,0.481602,0.512096,0.490908,0.499815,0.509059,0.518902,0.500439
1,0.497660,0.508092,0.502621,0.511139,0.512052,0.496358,0.517294,0.484007,0.484905,0.484301,...,0.502790,0.498517,0.507169,0.492199,0.504854,0.487932,0.491197,0.498660,0.495962,0.498620
2,0.494887,0.493517,0.489109,0.505441,0.505573,0.506662,0.511033,0.498191,0.496256,0.502946,...,0.503884,0.509765,0.505900,0.486689,0.509614,0.486803,0.496413,0.496269,0.522569,0.500209
3,0.483699,0.493694,0.484843,0.490301,0.483299,0.495117,0.508459,0.483418,0.485642,0.474540,...,0.487887,0.501003,0.500486,0.482652,0.496485,0.479274,0.491615,0.476385,0.499484,0.483884
4,0.475283,0.473498,0.475315,0.481674,0.478649,0.485214,0.488087,0.471654,0.471719,0.479022,...,0.471435,0.484388,0.483534,0.465447,0.492962,0.479178,0.469451,0.485311,0.486197,0.474825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.490189,0.494464,0.485565,0.498071,0.503195,0.509311,0.507333,0.501499,0.494527,0.494045,...,0.497867,0.504410,0.497863,0.489161,0.515575,0.493319,0.500058,0.502607,0.517716,0.507891
1678,0.494718,0.503851,0.491182,0.503051,0.493338,0.503275,0.516051,0.492597,0.498500,0.491148,...,0.502770,0.515094,0.505702,0.493787,0.501120,0.499566,0.491295,0.498138,0.517042,0.492145
1679,0.508660,0.505721,0.510581,0.502481,0.517850,0.511124,0.525370,0.499149,0.506032,0.501519,...,0.509003,0.513719,0.507104,0.498833,0.511654,0.503537,0.504967,0.512950,0.523436,0.508005
1680,0.504403,0.502487,0.499311,0.505996,0.515986,0.522348,0.522546,0.509335,0.495454,0.493519,...,0.509114,0.520474,0.507720,0.489935,0.510247,0.502910,0.496247,0.515653,0.522947,0.505320
1681,0.480804,0.486848,0.482855,0.497837,0.488575,0.490024,0.510652,0.489809,0.471648,0.482364,...,0.493119,0.484910,0.490130,0.472241,0.494905,0.486507,0.487598,0.488786,0.506273,0.486352

In [41]:
user_pred_Trans[34]

0       0.524206
1       0.507720
2       0.515472
3       0.503965
4       0.497283
          ...
1677    0.510203
1678    0.513482
1679    0.522587
1680    0.532801
1681    0.508311
Name: 34, Length: 1682, dtype: float64

In [42]:
gg=user_pred_Trans[34]

In [43]:
gg

0       0.524206
1       0.507720
2       0.515472
3       0.503965
4       0.497283
          ...
1677    0.510203
1678    0.513482
1679    0.522587
1680    0.532801
1681    0.508311
Name: 34, Length: 1682, dtype: float64

In [44]:
g=pd.DataFrame(gg)

In [45]:
g

            34
0     0.524206
1     0.507720
2     0.515472
3     0.503965
4     0.497283
...        ...
1677  0.510203
1678  0.513482
1679  0.522587
1680  0.532801
1681  0.508311

[1682 rows x 1 columns]

In [46]:
s=g.T

In [47]:
s

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
34,0.524206,0.50772,0.515472,0.503965,0.497283,0.495888,0.515567,0.505525,0.524523,0.517558,...,0.514423,0.491227,0.523736,0.507493,0.514818,0.510203,0.513482,0.522587,0.532801,0.508311

In [48]:
s[187].values>=0.4

array([ True])

In [49]:
highest_rated=[]
input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
input_user_pred=input_user_pre.T
for re in recom:
    value=input_user_pred[re].values
    if(value>=0.5):
        highest_rated.append(re)

In [50]:
len(highest_rated)

154

In [51]:
i_cols=["movie_id", 
    "title", 
    "release_date", 
    "video_release_date", 
    "IMDb_url",
    "unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", 
    "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", 
    "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"]
items=pd.read_csv('ml-100k/u.item',sep="|", names=i_cols, encoding="latin-1")

In [52]:
movie_title = []
for movieid in highest_rated:
    mov = items[items['movie_id'] == movieid]  # Compare movie_id with movieid directly
    movie_title.append(mov)

In [53]:
movie_title

[   movie_id             title release_date  video_release_date  \
 0         1  Toy Story (1995)  01-Jan-1995                 NaN

                                             IMDb_url  unknown  Action  \
 0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
 0          0          1           1  ...        0          0       0        0

    Mystery  Romance  Sci-Fi  Thriller  War  Western
 0        0        0       0         0    0        0

 [1 rows x 24 columns],
       movie_id                   title release_date  video_release_date  \
 1024      1025  Fire Down Below (1997)  01-Jan-1997                 NaN

                                                IMDb_url  unknown  Action  \
 1024  http://us.imdb.com/M/title-exact?Fire+Down+Bel...        0       1

       Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 1024          0          0           0  ...        0          0       0

       Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 1024        0        0        0       0         1    0        0

 [1 rows x 24 columns],
      movie_id             title release_date  video_release_date  \
 514       515  Boot, Das (1981)  04-Apr-1997                 NaN

                                               IMDb_url  unknown  Action  \
 514  http://us.imdb.com/M/title-exact?Boot,%20Das%2...        0       1

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 514          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 514        0        0        0       0         0    1        0

 [1 rows x 24 columns],
    movie_id              title release_date  video_release_date  \
 2         3  Four Rooms (1995)  01-Jan-1995                 NaN

                                             IMDb_url  unknown  Action  \
 2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
 2          0          0           0  ...        0          0       0        0

    Mystery  Romance  Sci-Fi  Thriller  War  Western
 2        0        0       0         1    0        0

 [1 rows x 24 columns],
    movie_id                  title release_date  video_release_date  \
 6         7  Twelve Monkeys (1995)  01-Jan-1995                 NaN

                                             IMDb_url  unknown  Action  \
 6  http://us.imdb.com/M/title-exact?Twelve%20Monk...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
 6          0          0           0  ...        0          0       0        0

    Mystery  Romance  Sci-Fi  Thriller  War  Western
 6        0        0       1         0    0        0

 [1 rows x 24 columns],
       movie_id                     title release_date  video_release_date  \
 1544      1545  Frankie Starlight (1995)  01-Jan-1995                 NaN

                                                IMDb_url  unknown  Action  \
 1544  http://us.imdb.com/M/title-exact?Frankie%20Sta...        0       0

       Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 1544          0          0           0  ...        0          0       0

       Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 1544        0        0        1       0         0    0        0

 [1 rows x 24 columns],
    movie_id                    title release_date  video_release_date  \
 8         9  Dead Man Walking (1995)  01-Jan-1995                 NaN

                                             IMDb_url  unknown  Action  \
 8  http://us.imdb.com/M/title-exact?Dead%20Man%20...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
 8          0          0           0  ...        0          0       0        0

    Mystery  Romance  Sci-Fi  Thriller  War  Western
 8        0        0       0         0    0        0

 [1 rows x 24 columns],
     movie_id                       title release_date  video_release_date  \
 11        12  Usual Suspects, The (1995)  14-Aug-1995                 NaN

                                              IMDb_url  unknown  Action  \
 11  http://us.imdb.com/M/title-exact?Usual%20Suspe...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 11          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 11        0        0        0       0         1    0        0

 [1 rows x 24 columns],
     movie_id                    title release_date  video_release_date  \
 12        13  Mighty Aphrodite (1995)  30-Oct-1995                 NaN

                                              IMDb_url  unknown  Action  \
 12  http://us.imdb.com/M/title-exact?Mighty%20Aphr...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 12          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 12        0        0        0       0         0    0        0

 [1 rows x 24 columns],
     movie_id               title release_date  video_release_date  \
 13        14  Postino, Il (1994)  01-Jan-1994                 NaN

                                              IMDb_url  unknown  Action  \
 13  http://us.imdb.com/M/title-exact?Postino,%20Il...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 13          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 13        0        0        1       0         0    0        0

 [1 rows x 24 columns],
      movie_id                  title release_date  video_release_date  \
 524       525  Big Sleep, The (1946)  01-Jan-1946                 NaN

                                               IMDb_url  unknown  Action  \
 524  http://us.imdb.com/M/title-exact?Big%20Sleep,%...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 524          0          0           0  ...        0          1       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 524        0        1        0       0         0    0        0

 [1 rows x 24 columns],
     movie_id                      title release_date  video_release_date  \
 14        15  Mr. Holland's Opus (1995)  29-Jan-1996                 NaN

                                              IMDb_url  unknown  Action  \
 14  http://us.imdb.com/M/title-exact?Mr.%20Holland...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 14          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 14        0        0        0       0         0    0        0

 [1 rows x 24 columns],
     movie_id                       title release_date  video_release_date  \
 16        17  From Dusk Till Dawn (1996)  05-Feb-1996                 NaN

                                              IMDb_url  unknown  Action  \
 16  http://us.imdb.com/M/title-exact?From%20Dusk%2...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 16          0          0           0  ...        0          0       1

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 16        0        0        0       0         1    0        0

 [1 rows x 24 columns],
      movie_id                              title release_date  \
 531       532  Kama Sutra: A Tale of Love (1996)  07-Mar-1997

      video_release_date                                           IMDb_url  \
 531                 NaN  http://us.imdb.com/M/title-exact?Kama%20Sutra%...

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
 531        0       0          0          0           0  ...        0

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
 531          0       0        0        0        1       0         0    0

      Western
 531        0

 [1 rows x 24 columns],
       movie_id                title release_date  video_release_date  \
 1046      1047  Multiplicity (1996)  12-Jul-1996                 NaN

                                                IMDb_url  unknown  Action  \
 1046  http://us.imdb.com/M/title-exact?Multiplicity%...        0       0

       Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 1046          0          0           0  ...        0          0       0

       Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 1046        0        0        0       0         0    0        0

 [1 rows x 24 columns],
     movie_id                       title release_date  video_release_date  \
 23        24  Rumble in the Bronx (1995)  23-Feb-1996                 NaN

                                              IMDb_url  unknown  Action  \
 23  http://us.imdb.com/M/title-exact?Hong%20Faan%2...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 23          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 23        0        0        0       0         0    0        0

 [1 rows x 24 columns],
     movie_id                 title release_date  video_release_date  \
 24        25  Birdcage, The (1996)  08-Mar-1996                 NaN

                                              IMDb_url  unknown  Action  \
 24  http://us.imdb.com/M/title-exact?Birdcage,%20T...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 24          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 24        0        0        0       0         0    0        0

 [1 rows x 24 columns],
       movie_id                  title release_date  video_release_date  \
 1050      1051  Associate, The (1996)  19-Oct-1996                 NaN

                                                IMDb_url  unknown  Action  \
 1050  http://us.imdb.com/M/title-exact?Associate,%20...        0       0

       Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 1050          0          0           0  ...        0          0       0

       Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 1050        0        0        0       0         0    0        0

 [1 rows x 24 columns],
      movie_id              title release_date  video_release_date  \
 538       539  Mouse Hunt (1997)  01-Jan-1997                 NaN

                                               IMDb_url  unknown  Action  \
 538  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 538          0          0           1  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 538        0        0        0       0         0    0        0

 [1 rows x 24 columns],
     movie_id                title release_date  video_release_date  \
 30        31  Crimson Tide (1995)  01-Jan-1995                 NaN

                                              IMDb_url  unknown  Action  \
 30  http://us.imdb.com/M/title-exact?Crimson%20Tid...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 30          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 30        0        0        0       0         1    1        0

 [1 rows x 24 columns],
      movie_id                title release_date  video_release_date  \
 545       546  Broken Arrow (1996)  09-Feb-1996                 NaN

                                               IMDb_url  unknown  Action  \
 545  http://us.imdb.com/M/title-exact?Broken%20Arro...        0       1

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 545          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 545        0        0        0       0         1    0        0

 [1 rows x 24 columns],
       movie_id                      title release_date  video_release_date  \
 1062      1063  Little Princess, A (1995)  01-Jan-1995                 NaN

                                                IMDb_url  unknown  Action  \
 1062  http://us.imdb.com/M/title-exact?Little%20Prin...        0       0

       Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 1062          0          0           1  ...        0          0       0

       Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 1062        0        0        0       0         0    0        0

 [1 rows x 24 columns],
     movie_id                       title release_date  video_release_date  \
 44        45  Eat Drink Man Woman (1994)  01-Jan-1994                 NaN

                                              IMDb_url  unknown  Action  \
 44  http://us.imdb.com/M/title-exact?Yinshi%20Nan%...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 44          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 44        0        0        0       0         0    0        0

 [1 rows x 24 columns],
       movie_id                 title release_date  video_release_date  \
 1072      1073  Shallow Grave (1994)  01-Jan-1994                 NaN

                                            IMDb_url  unknown  Action  \
 1072  http://us.imdb.com/Title?Shallow+Grave+(1994)        0       0

       Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 1072          0          0           0  ...        0          0       0

       Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 1072        0        0        0       0         1    0        0

 [1 rows x 24 columns],
     movie_id                     title release_date  video_release_date  \
 54        55  Professional, The (1994)  01-Jan-1994                 NaN

                                   IMDb_url  unknown  Action  Adventure  \
 54  http://us.imdb.com/Title?L%E9on+(1994)        0       0          0

     Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  Mystery  \
 54          0           0  ...        0          0       0        0        0

     Romance  Sci-Fi  Thriller  War  Western
 54        1       0         1    0        0

 [1 rows x 24 columns],
     movie_id                title release_date  video_release_date  \
 55        56  Pulp Fiction (1994)  01-Jan-1994                 NaN

                                              IMDb_url  unknown  Action  \
 55  http://us.imdb.com/M/title-exact?Pulp%20Fictio...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 55          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 55        0        0        0       0         0    0        0

 [1 rows x 24 columns],
       movie_id                           title release_date  \
 1088      1089  Speed 2: Cruise Control (1997)  13-Jun-1997

       video_release_date                                           IMDb_url  \
 1088                 NaN  http://us.imdb.com/M/title-exact?Speed%202%3A%...

       unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
 1088        0       1          0          0           0  ...        0

       Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
 1088          0       0        0        0        1       0         1    0

       Western
 1088        0

 [1 rows x 24 columns],
      movie_id              title release_date  video_release_date  \
 580       581  Kalifornia (1993)  01-Jan-1993                 NaN

                                               IMDb_url  unknown  Action  \
 580  http://us.imdb.com/M/title-exact?Kalifornia%20...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 580          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 580        0        0        0       0         1    0        0

 [1 rows x 24 columns],
      movie_id            title release_date  video_release_date  \
 594       595  Fan, The (1996)  16-Aug-1996                 NaN

                                               IMDb_url  unknown  Action  \
 594  http://us.imdb.com/M/title-exact?Fan,%20The%20...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 594          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 594        0        0        0       0         1    0        0

 [1 rows x 24 columns],
      movie_id          title release_date  video_release_date  \
 596       597  Eraser (1996)  21-Jun-1996                 NaN

                                              IMDb_url  unknown  Action  \
 596  http://us.imdb.com/M/title-exact?Eraser%20(1996)        0       1

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 596          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 596        0        0        0       0         1    0        0

 [1 rows x 24 columns],
      movie_id               title release_date  video_release_date  \
 602       603  Rear Window (1954)  01-Jan-1954                 NaN

                                               IMDb_url  unknown  Action  \
 602  http://us.imdb.com/M/title-exact?Rear%20Window...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 602          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 602        0        1        0       0         1    0        0

 [1 rows x 24 columns],
     movie_id                             title release_date  \
 97        98  Silence of the Lambs, The (1991)  01-Jan-1991

     video_release_date                                           IMDb_url  \
 97                 NaN  http://us.imdb.com/M/title-exact?Silence%20of%...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
 97        0       0          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
 97          0       0        0        0        0       0         1    0

     Western
 97        0

 [1 rows x 24 columns],
     movie_id         title release_date  video_release_date  \
 99       100  Fargo (1996)  14-Feb-1997                 NaN

                                            IMDb_url  unknown  Action  \
 99  http://us.imdb.com/M/title-exact?Fargo%20(1996)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
 99          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
 99        0        0        0       0         1    0        0

 [1 rows x 24 columns],
      movie_id                title release_date  video_release_date  \
 619       620  Chamber, The (1996)  11-Oct-1996                 NaN

                                               IMDb_url  unknown  Action  \
 619  http://us.imdb.com/M/title-exact?Chamber,%20Th...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \

In [54]:
movie_title_list = []
for m in movie_title: 
    print(m)
    mv =list(m)
    movie_title_list.append(mv)

   movie_id             title release_date  video_release_date  \
0         1  Toy Story (1995)  01-Jan-1995                 NaN

                                            IMDb_url  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0

   Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
0          0          1           1  ...        0          0       0        0

   Mystery  Romance  Sci-Fi  Thriller  War  Western
0        0        0       0         0    0        0

[1 rows x 24 columns]
      movie_id                   title release_date  video_release_date  \
1024      1025  Fire Down Below (1997)  01-Jan-1997                 NaN

                                               IMDb_url  unknown  Action  \
1024  http://us.imdb.com/M/title-exact?Fire+Down+Bel...        0       1

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1024          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1024        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
514       515  Boot, Das (1981)  04-Apr-1997                 NaN

                                              IMDb_url  unknown  Action  \
514  http://us.imdb.com/M/title-exact?Boot,%20Das%2...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
514          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
514        0        0        0       0         0    1        0

[1 rows x 24 columns]
   movie_id              title release_date  video_release_date  \
2         3  Four Rooms (1995)  01-Jan-1995                 NaN

                                            IMDb_url  unknown  Action  \
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0

   Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
2          0          0           0  ...        0          0       0        0

   Mystery  Romance  Sci-Fi  Thriller  War  Western
2        0        0       0         1    0        0

[1 rows x 24 columns]
   movie_id                  title release_date  video_release_date  \
6         7  Twelve Monkeys (1995)  01-Jan-1995                 NaN

                                            IMDb_url  unknown  Action  \
6  http://us.imdb.com/M/title-exact?Twelve%20Monk...        0       0

   Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
6          0          0           0  ...        0          0       0        0

   Mystery  Romance  Sci-Fi  Thriller  War  Western
6        0        0       1         0    0        0

[1 rows x 24 columns]
      movie_id                     title release_date  video_release_date  \
1544      1545  Frankie Starlight (1995)  01-Jan-1995                 NaN

                                               IMDb_url  unknown  Action  \
1544  http://us.imdb.com/M/title-exact?Frankie%20Sta...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1544          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1544        0        0        1       0         0    0        0

[1 rows x 24 columns]
   movie_id                    title release_date  video_release_date  \
8         9  Dead Man Walking (1995)  01-Jan-1995                 NaN

                                            IMDb_url  unknown  Action  \
8  http://us.imdb.com/M/title-exact?Dead%20Man%20...        0       0

   Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
8          0          0           0  ...        0          0       0        0

   Mystery  Romance  Sci-Fi  Thriller  War  Western
8        0        0       0         0    0        0

[1 rows x 24 columns]
    movie_id                       title release_date  video_release_date  \
11        12  Usual Suspects, The (1995)  14-Aug-1995                 NaN

                                             IMDb_url  unknown  Action  \
11  http://us.imdb.com/M/title-exact?Usual%20Suspe...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
11          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
11        0        0        0       0         1    0        0

[1 rows x 24 columns]
    movie_id                    title release_date  video_release_date  \
12        13  Mighty Aphrodite (1995)  30-Oct-1995                 NaN

                                             IMDb_url  unknown  Action  \
12  http://us.imdb.com/M/title-exact?Mighty%20Aphr...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
12          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
12        0        0        0       0         0    0        0

[1 rows x 24 columns]
    movie_id               title release_date  video_release_date  \
13        14  Postino, Il (1994)  01-Jan-1994                 NaN

                                             IMDb_url  unknown  Action  \
13  http://us.imdb.com/M/title-exact?Postino,%20Il...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
13          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
13        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
524       525  Big Sleep, The (1946)  01-Jan-1946                 NaN

                                              IMDb_url  unknown  Action  \
524  http://us.imdb.com/M/title-exact?Big%20Sleep,%...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
524          0          0           0  ...        0          1       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
524        0        1        0       0         0    0        0

[1 rows x 24 columns]
    movie_id                      title release_date  video_release_date  \
14        15  Mr. Holland's Opus (1995)  29-Jan-1996                 NaN

                                             IMDb_url  unknown  Action  \
14  http://us.imdb.com/M/title-exact?Mr.%20Holland...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
14          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
14        0        0        0       0         0    0        0

[1 rows x 24 columns]
    movie_id                       title release_date  video_release_date  \
16        17  From Dusk Till Dawn (1996)  05-Feb-1996                 NaN

                                             IMDb_url  unknown  Action  \
16  http://us.imdb.com/M/title-exact?From%20Dusk%2...        0       1

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
16          0          0           0  ...        0          0       1

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
16        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                              title release_date  \
531       532  Kama Sutra: A Tale of Love (1996)  07-Mar-1997

     video_release_date                                           IMDb_url  \
531                 NaN  http://us.imdb.com/M/title-exact?Kama%20Sutra%...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
531        0       0          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
531          0       0        0        0        1       0         0    0

     Western
531        0

[1 rows x 24 columns]
      movie_id                title release_date  video_release_date  \
1046      1047  Multiplicity (1996)  12-Jul-1996                 NaN

                                               IMDb_url  unknown  Action  \
1046  http://us.imdb.com/M/title-exact?Multiplicity%...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1046          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1046        0        0        0       0         0    0        0

[1 rows x 24 columns]
    movie_id                       title release_date  video_release_date  \
23        24  Rumble in the Bronx (1995)  23-Feb-1996                 NaN

                                             IMDb_url  unknown  Action  \
23  http://us.imdb.com/M/title-exact?Hong%20Faan%2...        0       1

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
23          1          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
23        0        0        0       0         0    0        0

[1 rows x 24 columns]

    movie_id                 title release_date  video_release_date  \
24        25  Birdcage, The (1996)  08-Mar-1996                 NaN

                                             IMDb_url  unknown  Action  \
24  http://us.imdb.com/M/title-exact?Birdcage,%20T...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
24          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
24        0        0        0       0         0    0        0

[1 rows x 24 columns]
      movie_id                  title release_date  video_release_date  \
1050      1051  Associate, The (1996)  19-Oct-1996                 NaN

                                               IMDb_url  unknown  Action  \
1050  http://us.imdb.com/M/title-exact?Associate,%20...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1050          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1050        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
538       539  Mouse Hunt (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
538  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
538          0          0           1  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
538        0        0        0       0         0    0        0

[1 rows x 24 columns]
    movie_id                title release_date  video_release_date  \
30        31  Crimson Tide (1995)  01-Jan-1995                 NaN

                                             IMDb_url  unknown  Action  \
30  http://us.imdb.com/M/title-exact?Crimson%20Tid...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
30          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
30        0        0        0       0         1    1        0

[1 rows x 24 columns]
     movie_id                title release_date  video_release_date  \
545       546  Broken Arrow (1996)  09-Feb-1996                 NaN

                                              IMDb_url  unknown  Action  \
545  http://us.imdb.com/M/title-exact?Broken%20Arro...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
545          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
545        0        0        0       0         1    0        0

[1 rows x 24 columns]
      movie_id                      title release_date  video_release_date  \
1062      1063  Little Princess, A (1995)  01-Jan-1995                 NaN

                                               IMDb_url  unknown  Action  \
1062  http://us.imdb.com/M/title-exact?Little%20Prin...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1062          0          0           1  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1062        0        0        0       0         0    0        0

[1 rows x 24 columns]
    movie_id                       title release_date  video_release_date  \
44        45  Eat Drink Man Woman (1994)  01-Jan-1994                 NaN

                                             IMDb_url  unknown  Action  \
44  http://us.imdb.com/M/title-exact?Yinshi%20Nan%...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
44          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
44        0        0        0       0         0    0        0

[1 rows x 24 columns]
      movie_id                 title release_date  video_release_date  \
1072      1073  Shallow Grave (1994)  01-Jan-1994                 NaN

                                           IMDb_url  unknown  Action  \
1072  http://us.imdb.com/Title?Shallow+Grave+(1994)        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1072          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1072        0        0        0       0         1    0        0

[1 rows x 24 columns]
    movie_id                     title release_date  video_release_date  \
54        55  Professional, The (1994)  01-Jan-1994                 NaN

                                  IMDb_url  unknown  Action  Adventure  \
54  http://us.imdb.com/Title?L%E9on+(1994)        0       0          0

    Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  Mystery  \
54          0           0  ...        0          0       0        0        0

    Romance  Sci-Fi  Thriller  War  Western
54        1       0         1    0        0

[1 rows x 24 columns]
    movie_id                title release_date  video_release_date  \
55        56  Pulp Fiction (1994)  01-Jan-1994                 NaN

                                             IMDb_url  unknown  Action  \
55  http://us.imdb.com/M/title-exact?Pulp%20Fictio...        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
55          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
55        0        0        0       0         0    0        0

[1 rows x 24 columns]
      movie_id                           title release_date  \
1088      1089  Speed 2: Cruise Control (1997)  13-Jun-1997

      video_release_date                                           IMDb_url  \
1088                 NaN  http://us.imdb.com/M/title-exact?Speed%202%3A%...

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
1088        0       1          0          0           0  ...        0

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
1088          0       0        0        0        1       0         1    0

      Western
1088        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
580       581  Kalifornia (1993)  01-Jan-1993                 NaN

                                              IMDb_url  unknown  Action  \
580  http://us.imdb.com/M/title-exact?Kalifornia%20...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
580          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
580        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id            title release_date  video_release_date  \
594       595  Fan, The (1996)  16-Aug-1996                 NaN

                                              IMDb_url  unknown  Action  \
594  http://us.imdb.com/M/title-exact?Fan,%20The%20...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
594          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
594        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id          title release_date  video_release_date  \
596       597  Eraser (1996)  21-Jun-1996                 NaN

                                             IMDb_url  unknown  Action  \
596  http://us.imdb.com/M/title-exact?Eraser%20(1996)        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
596          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
596        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id               title release_date  video_release_date  \
602       603  Rear Window (1954)  01-Jan-1954                 NaN

                                              IMDb_url  unknown  Action  \
602  http://us.imdb.com/M/title-exact?Rear%20Window...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
602          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
602        0        1        0       0         1    0        0

[1 rows x 24 columns]
    movie_id                             title release_date  \
97        98  Silence of the Lambs, The (1991)  01-Jan-1991

    video_release_date                                           IMDb_url  \
97                 NaN  http://us.imdb.com/M/title-exact?Silence%20of%...

    unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
97        0       0          0          0           0  ...        0

    Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
97          0       0        0        0        0       0         1    0

    Western
97        0

[1 rows x 24 columns]
    movie_id         title release_date  video_release_date  \
99       100  Fargo (1996)  14-Feb-1997                 NaN

                                           IMDb_url  unknown  Action  \
99  http://us.imdb.com/M/title-exact?Fargo%20(1996)        0       0

    Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
99          0          0           0  ...        0          0       0

    Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
99        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                title release_date  video_release_date  \
619       620  Chamber, The (1996)  11-Oct-1996                 NaN

                                              IMDb_url  unknown  Action  \
619  http://us.imdb.com/M/title-exact?Chamber,%20Th...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
619          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
619        0        0        0       0         0    0        0

[1 rows x 24 columns]

     movie_id             title release_date  video_release_date  \
116       117  Rock, The (1996)  07-Jun-1996                 NaN

                                              IMDb_url  unknown  Action  \
116  http://us.imdb.com/M/title-exact?Rock,%20The%2...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
116          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
116        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                          title release_date  video_release_date  \
120       121  Independence Day (ID4) (1996)  03-Jul-1996                 NaN

                                              IMDb_url  unknown  Action  \
120  http://us.imdb.com/M/title-exact?Independence%...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
120          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
120        0        0        0       1         0    1        0

[1 rows x 24 columns]
     movie_id                        title release_date  video_release_date  \
635       636  Escape from New York (1981)  01-Jan-1981                 NaN

                                              IMDb_url  unknown  Action  \
635  http://us.imdb.com/M/title-exact?Escape%20from...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
635          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
635        0        0        0       1         1    0        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
126       127  Godfather, The (1972)  01-Jan-1972                 NaN

                                              IMDb_url  unknown  Action  \
126  http://us.imdb.com/M/title-exact?Godfather,%20...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
126          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
126        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                 title release_date  video_release_date  \
641       642  Grifters, The (1990)  01-Jan-1990                 NaN

                                              IMDb_url  unknown  Action  \
641  http://us.imdb.com/M/title-exact?Grifters,%20T...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
641          0          0           0  ...        0          1       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
641        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                               title release_date  \
648       649  Once Upon a Time in America (1984)  01-Jan-1984

     video_release_date                                           IMDb_url  \
648                 NaN  http://us.imdb.com/M/title-exact?Once%20Upon%2...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
648        0       0          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
648          0       0        0        0        0       0         1    0

     Western
648        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
653       654  Chinatown (1974)  01-Jan-1974                 NaN

                                              IMDb_url  unknown  Action  \
653  http://us.imdb.com/M/title-exact?Chinatown%20(...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
653          0          0           0  ...        0          1       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
653        0        1        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                             title release_date  \
656       657  Manchurian Candidate, The (1962)  01-Jan-1962

     video_release_date                                           IMDb_url  \
656                 NaN  http://us.imdb.com/M/title-exact?Manchurian%20...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
656        0       0          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
656          1       0        0        0        0       0         1    0

     Western
656        0

[1 rows x 24 columns]
     movie_id                            title release_date  \
146       147  Long Kiss Goodnight, The (1996)  05-Oct-1996

     video_release_date                                           IMDb_url  \
146                 NaN  http://us.imdb.com/M/title-exact?Long%20Kiss%2...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
146        0       1          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
146          0       0        0        0        0       0         1    0

     Western
146        0

[1 rows x 24 columns]
     movie_id                        title release_date  video_release_date  \
658       659  Arsenic and Old Lace (1944)  01-Jan-1944                 NaN

                                              IMDb_url  unknown  Action  \
658  http://us.imdb.com/M/title-exact?Arsenic%20and...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
658          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
658        0        1        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                                         title release_date  \
150       151  Willy Wonka and the Chocolate Factory (1971)  01-Jan-1971

     video_release_date                                           IMDb_url  \
150                 NaN  http://us.imdb.com/M/title-exact?Willy%20Wonka...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
150        0       0          1          0           1  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
150          0       0        0        0        0       0         0    0

     Western
150        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
155       156  Reservoir Dogs (1992)  01-Jan-1992                 NaN

                                              IMDb_url  unknown  Action  \
155  http://us.imdb.com/M/title-exact?Reservoir%20D...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
155          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
155        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
163       164  Abyss, The (1989)  01-Jan-1989                 NaN

                                              IMDb_url  unknown  Action  \
163  http://us.imdb.com/M/title-exact?Abyss,%20The%...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
163          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
163        0        0        0       1         1    0        0

[1 rows x 24 columns]
     movie_id           title release_date  video_release_date  \
677       678  Volcano (1997)  25-Apr-1997                 NaN

                                              IMDb_url  unknown  Action  \
677  http://us.imdb.com/M/title-exact?Volcano%20%28...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
677          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
677        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                                   title release_date  \
681       682  I Know What You Did Last Summer (1997)  17-Oct-1997

     video_release_date                                           IMDb_url  \
681                 NaN  http://us.imdb.com/M/title-exact?I+Know+What+Y...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
681        0       0          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
681          0       1        0        1        0       0         1    0

     Western
681        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
682       683  Rocket Man (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
682  http://us.imdb.com/M/title-exact?Rocket+Man+(1...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
682          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
682        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                       title release_date  video_release_date  \
172       173  Princess Bride, The (1987)  01-Jan-1987                 NaN

                                              IMDb_url  unknown  Action  \
172  http://us.imdb.com/M/title-exact?Princess%20Br...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
172          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
172        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id                           title release_date  \
173       174  Raiders of the Lost Ark (1981)  01-Jan-1981

     video_release_date                                           IMDb_url  \
173                 NaN  http://us.imdb.com/M/title-exact?Raiders%20of%...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
173        0       1          1          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
173          0       0        0        0        0       0         0    0

     Western
173        0

[1 rows x 24 columns]
     movie_id          title release_date  video_release_date  \
175       176  Aliens (1986)  01-Jan-1986                 NaN

                                             IMDb_url  unknown  Action  \
175  http://us.imdb.com/M/title-exact?Aliens%20(1986)        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
175          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
175        0        0        0       1         1    1        0

[1 rows x 24 columns]
     movie_id               title release_date  video_release_date  \
688       689  Jackal, The (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
688  http://us.imdb.com/M/title-exact?Jackal%2C+The...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
688          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
688        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                      title release_date  video_release_date  \
180       181  Return of the Jedi (1983)  14-Mar-1997                 NaN

                                              IMDb_url  unknown  Action  \
180  http://us.imdb.com/M/title-exact?Return%20of%2...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
180          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
180        0        0        1       1         0    1        0

[1 rows x 24 columns]
     movie_id         title release_date  video_release_date  \
182       183  Alien (1979)  01-Jan-1979                 NaN

                                            IMDb_url  unknown  Action  \
182  http://us.imdb.com/M/title-exact?Alien%20(1979)        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
182          0          0           0  ...        0          0       1

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
182        0        0        0       1         1    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
695       696  City Hall (1996)  16-Feb-1996                 NaN

                                              IMDb_url  unknown  Action  \
695  http://us.imdb.com/M/title-exact?City%20Hall%2...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
695          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
695        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id           title release_date  video_release_date  \
190       191  Amadeus (1984)  01-Jan-1984                 NaN

                                              IMDb_url  unknown  Action  \
190  http://us.imdb.com/M/title-exact?Amadeus%20(1984)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
190          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
190        0        1        0       0         0    0        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
202       203  Unforgiven (1992)  01-Jan-1992                 NaN

                                              IMDb_url  unknown  Action  \
202  http://us.imdb.com/M/title-exact?Unforgiven%20...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
202          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
202        0        0        0       0         0    0        1

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
716       717  Juror, The (1996)  01-Jan-1996                 NaN

                                              IMDb_url  unknown  Action  \
716  http://us.imdb.com/M/title-exact?Juror,%20The%...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
716          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
716        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
217       218  Cape Fear (1991)  01-Jan-1991                 NaN

                                              IMDb_url  unknown  Action  \
217  http://us.imdb.com/M/title-exact?Cape%20Fear%2...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
217          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
217        0        0        0       0         1    0        0

[1 rows x 24 columns]
      movie_id         title release_date  video_release_date  \
1243      1244  Metro (1997)  17-Jan-1997                 NaN

                                             IMDb_url  unknown  Action  \
1243  http://us.imdb.com/M/title-exact?Metro%20(1997)        0       1

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1243          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1243        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                            title release_date  \
221       222  Star Trek: First Contact (1996)  22-Nov-1996

     video_release_date                                           IMDb_url  \
221                 NaN  http://us.imdb.com/M/title-exact?Star%20Trek:%...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
221        0       1          1          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
221          0       0        0        0        0       1         0    0

     Western
221        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
224       225  101 Dalmatians (1996)  27-Nov-1996                 NaN

                                              IMDb_url  unknown  Action  \
224  http://us.imdb.com/M/title-exact?101%20Dalmati...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
224          0          0           1  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
224        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
225       226  Die Hard 2 (1990)  01-Jan-1990                 NaN

                                              IMDb_url  unknown  Action  \
225  http://us.imdb.com/M/title-exact?Die%20Hard%20...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
225          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
225        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                                       title release_date  \
228       229  Star Trek III: The Search for Spock (1984)  01-Jan-1984

     video_release_date                                           IMDb_url  \
228                 NaN  http://us.imdb.com/M/title-exact?Star%20Trek%2...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
228        0       1          1          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
228          0       0        0        0        0       1         0    0

     Western
228        0

[1 rows x 24 columns]

     movie_id          title release_date  video_release_date  \
741       742  Ransom (1996)  08-Nov-1996                 NaN

                                             IMDb_url  unknown  Action  \
741  http://us.imdb.com/M/title-exact?Ransom%20(1996)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
741          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
741        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id        title release_date  video_release_date  \
233       234  Jaws (1975)  01-Jan-1975                 NaN

                                           IMDb_url  unknown  Action  \
233  http://us.imdb.com/M/title-exact?Jaws%20(1975)        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
233          0          0           0  ...        0          0       1

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
233        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                 title release_date  video_release_date  \
234       235  Mars Attacks! (1996)  13-Dec-1996                 NaN

                                              IMDb_url  unknown  Action  \
234  http://us.imdb.com/M/title-exact?Mars%20Attack...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
234          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
234        0        0        0       1         0    1        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
747       748  Saint, The (1997)  14-Mar-1997                 NaN

                                              IMDb_url  unknown  Action  \
747  http://us.imdb.com/M/title-exact?Saint%2C%20Th...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
747          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
747        0        0        1       0         1    0        0

[1 rows x 24 columns]
     movie_id           title release_date  video_release_date  \
749       750  Amistad (1997)  18-Dec-1997                 NaN

                                              IMDb_url  unknown  Action  \
749  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
749          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
749        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                       title release_date  video_release_date  \
247       248  Grosse Pointe Blank (1997)  11-Apr-1997                 NaN

                                              IMDb_url  unknown  Action  \
247  http://us.imdb.com/M/title-exact?Grosse%20Poin...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
247          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
247        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
759       760  Screamers (1995)  01-Jan-1995                 NaN

                                              IMDb_url  unknown  Action  \
759  http://us.imdb.com/M/title-exact?Screamers%20(...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
759          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
759        0        0        0       1         0    0        0

[1 rows x 24 columns]
     movie_id                   title release_date  video_release_date  \
761       762  Beautiful Girls (1996)  09-Feb-1996                 NaN

                                              IMDb_url  unknown  Action  \
761  http://us.imdb.com/M/title-exact?Beautiful%20G...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
761          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
761        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                      title release_date  video_release_date  \
249       250  Fifth Element, The (1997)  09-May-1997                 NaN

                                              IMDb_url  unknown  Action  \
249  http://us.imdb.com/M/title-exact?Fifth%20Eleme...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
249          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
249        0        0        0       1         0    0        0

[1 rows x 24 columns]
     movie_id                                  title release_date  \
251       252  Lost World: Jurassic Park, The (1997)  23-May-1997

     video_release_date                                           IMDb_url  \
251                 NaN  http://us.imdb.com/M/title-exact?Lost%20World%...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
251        0       1          1          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
251          0       0        0        0        0       1         1    0

     Western
251        0

[1 rows x 24 columns]
      movie_id          title release_date  video_release_date  \
1277      1278  Selena (1997)  21-Mar-1997                 NaN

                                              IMDb_url  unknown  Action  \
1277  http://us.imdb.com/M/title-exact?Selena%20(1997)        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1277          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1277        1        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
253       254  Batman & Robin (1997)  20-Jun-1997                 NaN

                                              IMDb_url  unknown  Action  \
253  http://us.imdb.com/M/title-exact?Batman+%26+Ro...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
253          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
253        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                title release_date  video_release_date  \
256       257  Men in Black (1997)  04-Jul-1997                 NaN

                                              IMDb_url  unknown  Action  \
256  http://us.imdb.com/M/title-exact?Men+in+Black+...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
256          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
256        0        0        0       1         0    0        0

[1 rows x 24 columns]
     movie_id                 title release_date  video_release_date  \
259       260  Event Horizon (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
259  http://us.imdb.com/M/title-exact?Event+Horizon...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
259          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
259        0        1        0       1         1    0        0

[1 rows x 24 columns]
     movie_id         title release_date  video_release_date  \
263       264  Mimic (1997)  22-Aug-1997                 NaN

                                          IMDb_url  unknown  Action  \
263  http://us.imdb.com/M/title-exact?Mimic+(1997)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
263          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
263        0        0        0       1         1    0        0

[1 rows x 24 columns]
     movie_id               title release_date  video_release_date  \
267       268  Chasing Amy (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
267  http://us.imdb.com/M/title-exact?Chasing+Amy+(...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
267          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
267        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id                   title release_date  video_release_date  \
268       269  Full Monty, The (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
268  http://us.imdb.com/M/title-exact?Full+Monty%2C...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
268          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
268        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id           title release_date  video_release_date  \
269       270  Gattaca (1997)  01-Jan-1997                 NaN

                                            IMDb_url  unknown  Action  \
269  http://us.imdb.com/M/title-exact?Gattaca+(1997)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
269          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
269        0        0        0       1         1    0        0

[1 rows x 24 columns]
     movie_id                     title release_date  video_release_date  \
271       272  Good Will Hunting (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
271  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
271          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
271        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id        title release_date  video_release_date  \
272       273  Heat (1995)  01-Jan-1995                 NaN

                                           IMDb_url  unknown  Action  \
272  http://us.imdb.com/M/title-exact?Heat%20(1995)        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
272          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
272        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                         title release_date  video_release_date  \
274       275  Sense and Sensibility (1995)  01-Jan-1995                 NaN

                                              IMDb_url  unknown  Action  \
274  http://us.imdb.com/M/title-exact?Sense%20and%2...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
274          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
274        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id                     title release_date  video_release_date  \
275       276  Leaving Las Vegas (1995)  01-Jan-1995                 NaN

                                              IMDb_url  unknown  Action  \
275  http://us.imdb.com/M/title-exact?Leaving%20Las...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
275          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
275        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id               title release_date  video_release_date  \
276       277  Restoration (1995)  01-Jan-1995                 NaN

                                              IMDb_url  unknown  Action  \
276  http://us.imdb.com/M/title-exact?Restoration%2...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
276          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
276        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                   title release_date  video_release_date  \
280       281  River Wild, The (1994)  01-Jan-1994                 NaN

                                              IMDb_url  unknown  Action  \
280  http://us.imdb.com/M/title-exact?River%20Wild,...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
280          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
280        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                   title release_date  video_release_date  \
281       282  Time to Kill, A (1996)  13-Jul-1996                 NaN

                                              IMDb_url  unknown  Action  \
281  http://us.imdb.com/M/title-exact?Time%20to%20K...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
281          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
281        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id        title release_date  video_release_date  \
282       283  Emma (1996)  02-Aug-1996                 NaN

                                           IMDb_url  unknown  Action  \
282  http://us.imdb.com/M/title-exact?Emma%20(1996)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
282          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
282        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
290       291  Absolute Power (1997)  14-Feb-1997                 NaN

                                              IMDb_url  unknown  Action  \
290  http://us.imdb.com/M/title-exact?Absolute%20Po...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
290          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
290        0        1        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                 title release_date  video_release_date  \
292       293  Donnie Brasco (1997)  28-Feb-1997                 NaN

                                              IMDb_url  unknown  Action  \
292  http://us.imdb.com/M/title-exact?Donnie%20Bras...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
292          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
292        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
294       295  Breakdown (1997)  02-May-1997                 NaN

                                              IMDb_url  unknown  Action  \
294  http://us.imdb.com/M/title-exact?Breakdown%20%...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
294          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
294        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id            title release_date  video_release_date  \
297       298  Face/Off (1997)  27-Jun-1997                 NaN

                                             IMDb_url  unknown  Action  \
297  http://us.imdb.com/M/title-exact?Face/Off+(1997)        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
297          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
297        0        0        0       1         1    0        0

[1 rows x 24 columns]
     movie_id            title release_date  video_release_date  \
300       301  In & Out (1997)  19-Sep-1997                 NaN

                                       IMDb_url  unknown  Action  Adventure  \
300  http://us.imdb.com/Title?In+%26+Out+(1997)        0       0          0

     Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  Mystery  \
300          0           0  ...        0          0       0        0        0

     Romance  Sci-Fi  Thriller  War  Western
300        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                     title release_date  video_release_date  \
301       302  L.A. Confidential (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
301  http://us.imdb.com/M/title-exact?L%2EA%2E+Conf...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
301          0          0           0  ...        0          1       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
301        0        1        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
304       305  Ice Storm, The (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
304  http://us.imdb.com/M/title-exact?Ice+Storm%2C+...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
304          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
304        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                                        title release_date  \
305       306  Mrs. Brown (Her Majesty, Mrs. Brown) (1997)  01-Jan-1997

     video_release_date                                           IMDb_url  \
305                 NaN  http://us.imdb.com/M/title-exact?Her+Majesty%2...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
305        0       0          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
305          0       0        0        0        1       0         0    0

     Western
305        0

[1 rows x 24 columns]
     movie_id                         title release_date  video_release_date  \

     movie_id                      title release_date  video_release_date  \
315       316  As Good As It Gets (1997)  23-Dec-1997                 NaN

                                              IMDb_url  unknown  Action  \
315  http://us.imdb.com/Title?As+Good+As+It+Gets+(1...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
315          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
315        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                            title release_date  \
318       319  Everyone Says I Love You (1996)  06-Dec-1996

     video_release_date                                           IMDb_url  \
318                 NaN  http://us.imdb.com/M/title-exact?Everyone%20Sa...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
318        0       0          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
318          0       0        1        0        1       0         0    0

     Western
318        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
321       322  Murder at 1600 (1997)  18-Apr-1997                 NaN

                                              IMDb_url  unknown  Action  \
321  http://us.imdb.com/M/title-exact?Murder%20at%2...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
321          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
321        0        1        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                title release_date  video_release_date  \
322       323  Dante's Peak (1997)  07-Feb-1997                 NaN

                                              IMDb_url  unknown  Action  \
322  http://us.imdb.com/M/title-exact?Dante's%20Pea...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
322          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
322        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
325       326  G.I. Jane (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
325  http://us.imdb.com/M/title-exact?G%2EI%2E+Jane...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
325          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
325        0        0        0       0         0    1        0

[1 rows x 24 columns]
     movie_id            title release_date  video_release_date  \
326       327  Cop Land (1997)  01-Jan-1997                 NaN

                                             IMDb_url  unknown  Action  \
326  http://us.imdb.com/M/title-exact?Cop+Land+(1997)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
326          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
326        0        1        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                     title release_date  video_release_date  \
327       328  Conspiracy Theory (1997)  08-Aug-1997                 NaN

                                              IMDb_url  unknown  Action  \
327  http://us.imdb.com/M/title-exact?Conspiracy+Th...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
327          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
327        0        1        1       0         1    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
330       331  Edge, The (1997)  26-Sep-1997                 NaN

                                              IMDb_url  unknown  Action  \
330  http://us.imdb.com/M/title-exact?Edge%2C+The+(...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
330          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
330        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
332       333  Game, The (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
332  http://us.imdb.com/M/title-exact?Game%2C+The+(...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
332          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
332        0        1        0       0         1    0        0

[1 rows x 24 columns]
     movie_id        title release_date  video_release_date  \
337       338  Bean (1997)  01-Jan-1997                 NaN

                                         IMDb_url  unknown  Action  Adventure  \
337  http://us.imdb.com/M/title-exact?Bean+(1997)        0       0          0

     Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  Mystery  \
337          0           0  ...        0          0       0        0        0

     Romance  Sci-Fi  Thriller  War  Western
337        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                 title release_date  video_release_date  \
339       340  Boogie Nights (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
339  http://us.imdb.com/M/title-exact?Boogie+Nights...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
339          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
339        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                       title release_date  video_release_date  \
342       343  Alien: Resurrection (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
342  http://us.imdb.com/M/title-exact?Alien%3A+Resu...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
342          0          0           0  ...        0          0       1

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
342        0        0        0       1         0    0        0

[1 rows x 24 columns]
     movie_id                title release_date  video_release_date  \
343       344  Apostle, The (1997)  18-Dec-1997                 NaN

                                              IMDb_url  unknown  Action  \
343  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
343          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
343        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                        title release_date  video_release_date  \
344       345  Deconstructing Harry (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
344  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
344          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
344        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                title release_date  video_release_date  \
345       346  Jackie Brown (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
345  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
345          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
345        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id               title release_date  video_release_date  \
346       347  Wag the Dog (1997)  09-Jan-1998                 NaN

                                              IMDb_url  unknown  Action  \
346  http://us.imdb.com/M/title-exact?imdb-title-12...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
346          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
346        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                       title release_date  video_release_date  \
353       354  Wedding Singer, The (1998)  13-Feb-1998                 NaN

                                              IMDb_url  unknown  Action  \
353  http://us.imdb.com/M/title-exact?Wedding+Singe...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
353          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
353        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id           title release_date  video_release_date  \
865       866  Michael (1996)  25-Dec-1996                 NaN

                                              IMDb_url  unknown  Action  \
865  http://us.imdb.com/M/title-exact?Michael%20(1996)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
865          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
865        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id         title release_date  video_release_date  \
357       358  Spawn (1997)  01-Aug-1997                 NaN

                                            IMDb_url  unknown  Action  \
357  http://us.imdb.com/M/title-exact?Spawn+(1997/I)        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
357          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
357        0        0        0       1         1    0        0

[1 rows x 24 columns]
     movie_id                     title release_date  video_release_date  \
881       882  Washington Square (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
881  http://us.imdb.com/M/title-exact?Washington+Sq...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
881          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
881        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id               title release_date  video_release_date  \
369       370  Mary Reilly (1996)  23-Feb-1996                 NaN

                                              IMDb_url  unknown  Action  \
369  http://us.imdb.com/M/title-exact?Mary%20Reilly...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
369          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
369        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id               title release_date  video_release_date  \
886       887  Eve's Bayou (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
886  http://us.imdb.com/M/title-exact?Eve's+Bayou+(...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
886          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
886        0        0        0       0         0    0        0

[1 rows x 24 columns]
      movie_id                title release_date  video_release_date  \
1404      1405  Boy's Life 2 (1997)  07-Mar-1997                 NaN

                                               IMDb_url  unknown  Action  \
1404  http://us.imdb.com/M/title-exact?Boy%27s%20Lif...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1404          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1404        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id            title release_date  video_release_date  \
894       895  Scream 2 (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
894  http://us.imdb.com/M/title-exact?imdb-title-12...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
894          0          0           0  ...        0          0       1

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
894        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id             title release_date  video_release_date  \
902       903  Afterglow (1997)  26-Dec-1997                 NaN

                                              IMDb_url  unknown  Action  \
902  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
902          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
902        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id                      title release_date  video_release_date  \
904       905  Great Expectations (1998)  01-Jan-1998                 NaN

                                              IMDb_url  unknown  Action  \
904  http://us.imdb.com/M/title-exact?imdb-title-11...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
904          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
904        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id                       title release_date  video_release_date  \
404       405  Mission: Impossible (1996)  22-May-1996                 NaN

                                              IMDb_url  unknown  Action  \
404  http://us.imdb.com/M/title-exact?Mission:%20Im...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
404          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
404        0        1        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                        title release_date  video_release_date  \
410       411  Nutty Professor, The (1996)  28-Jun-1996                 NaN

                                              IMDb_url  unknown  Action  \
410  http://us.imdb.com/M/title-exact?Nutty%20Profe...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
410          0          0           0  ...        1          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
410        0        0        1       1         0    0        0

[1 rows x 24 columns]
     movie_id                 title release_date  video_release_date  \
924       925  Unforgettable (1996)  23-Feb-1996                 NaN

                                          IMDb_url  unknown  Action  \
924  http://us.imdb.com/Title?Unforgettable+(1996)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
924          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
924        0        0        0       1         1    0        0

[1 rows x 24 columns]

     movie_id                                              title release_date  \
412       413  Tales from the Crypt Presents: Bordello of Blo...  19-Jul-1996

     video_release_date                                           IMDb_url  \
412                 NaN  http://us.imdb.com/M/title-exact?Tales%20from%...

     unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
412        0       0          0          0           0  ...        0

     Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
412          0       1        0        0        0       0         0    0

     Western
412        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
927       928  Craft, The (1996)  26-Apr-1996                 NaN

                                              IMDb_url  unknown  Action  \
927  http://us.imdb.com/M/title-exact?Craft,%20The%...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
927          0          0           0  ...        0          0       1

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
927        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                       title release_date  video_release_date  \
937       938  Smile Like Yours, A (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
937  http://us.imdb.com/M/title-exact?Smile+Like+Yo...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
937          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
937        0        0        1       0         0    0        0

[1 rows x 24 columns]
     movie_id                         title release_date  video_release_date  \
426       427  To Kill a Mockingbird (1962)  01-Jan-1962                 NaN

                                              IMDb_url  unknown  Action  \
426  http://us.imdb.com/M/title-exact?To%20Kill%20a...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
426          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
426        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
430       431  Highlander (1986)  01-Jan-1986                 NaN

                                              IMDb_url  unknown  Action  \
430  http://us.imdb.com/M/title-exact?Highlander%20...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
430          1          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
430        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id              title release_date  video_release_date  \
442       443  Birds, The (1963)  01-Jan-1963                 NaN

                                              IMDb_url  unknown  Action  \
442  http://us.imdb.com/M/title-exact?Birds,%20The%...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
442          0          0           0  ...        0          0       1

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
442        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id         title release_date  video_release_date  \
457       458  Nixon (1995)  01-Jan-1995                 NaN

                                            IMDb_url  unknown  Action  \
457  http://us.imdb.com/M/title-exact?Nixon%20(1995)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
457          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
457        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                 title release_date  video_release_date  \
465       466  Red Rock West (1992)  01-Jan-1992                 NaN

                                              IMDb_url  unknown  Action  \
465  http://us.imdb.com/M/title-exact?Red%20Rock%20...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
465          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
465        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                      title release_date  video_release_date  \
977       978  Heaven's Prisoners (1996)  10-May-1996                 NaN

                                              IMDb_url  unknown  Action  \
977  http://us.imdb.com/M/title-exact?Heaven's%20Pr...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
977          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
977        0        1        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                      title release_date  video_release_date  \
470       471  Courage Under Fire (1996)  08-Mar-1996                 NaN

                                              IMDb_url  unknown  Action  \
470  http://us.imdb.com/M/title-exact?Courage%20Und...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
470          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
470        0        0        0       0         0    1        0

[1 rows x 24 columns]
     movie_id               title release_date  video_release_date  \
471       472  Dragonheart (1996)  31-May-1996                 NaN

                                              IMDb_url  unknown  Action  \
471  http://us.imdb.com/M/title-exact?Dragonheart%2...        0       1

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
471          1          0           0  ...        1          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
471        0        0        0       0         0    0        0

[1 rows x 24 columns]
      movie_id           title release_date  video_release_date  \
1015      1016  Con Air (1997)  06-Jun-1997                 NaN

                                               IMDb_url  unknown  Action  \
1015  http://us.imdb.com/M/title-exact?Con%20Air%20%...        0       1

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1015          1          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1015        0        0        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                 title release_date  video_release_date  \
474       475  Trainspotting (1996)  19-Jul-1996                 NaN

                                          IMDb_url  unknown  Action  \
474  http://us.imdb.com/Title?Trainspotting+(1996)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
474          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
474        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id           title release_date  video_release_date  \
476       477  Matilda (1996)  02-Aug-1996                 NaN

                                              IMDb_url  unknown  Action  \
476  http://us.imdb.com/M/title-exact?Matilda%20(1996)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
476          0          0           1  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
476        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id           title release_date  video_release_date  \
478       479  Vertigo (1958)  01-Jan-1958                 NaN

                                              IMDb_url  unknown  Action  \
478  http://us.imdb.com/M/title-exact?Vertigo%20(1958)        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
478          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
478        0        1        0       0         1    0        0

[1 rows x 24 columns]
     movie_id                  title release_date  video_release_date  \
994       995  Kiss Me, Guido (1997)  01-Jan-1997                 NaN

                                              IMDb_url  unknown  Action  \
994  http://us.imdb.com/M/title-exact?Kiss+Me%2C+Gu...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
994          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
994        0        0        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                       title release_date  video_release_date  \
483       484  Maltese Falcon, The (1941)  01-Jan-1941                 NaN

                                              IMDb_url  unknown  Action  \
483  http://us.imdb.com/M/title-exact?Maltese%20Fal...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
483          0          0           0  ...        0          1       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
483        0        1        0       0         0    0        0

[1 rows x 24 columns]
     movie_id                         title release_date  video_release_date  \
498       499  Cat on a Hot Tin Roof (1958)  01-Jan-1958                 NaN

                                              IMDb_url  unknown  Action  \
498  http://us.imdb.com/M/title-exact?Cat%20on%20a%...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
498          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
498        0        0        0       0         0    0        0

[1 rows x 24 columns]
      movie_id                        title release_date  video_release_date  \
1010      1011  2 Days in the Valley (1996)  27-Sep-1996                 NaN

                                               IMDb_url  unknown  Action  \
1010  http://us.imdb.com/M/title-exact?2%20Days%20in...        0       0

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1010          0          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1010        0        0        0       0         0    0        0

[1 rows x 24 columns]
      movie_id            title release_date  video_release_date  \
1012      1013  Anaconda (1997)  11-Apr-1997                 NaN

                                               IMDb_url  unknown  Action  \
1012  http://us.imdb.com/M/title-exact?Anaconda%20%2...        0       1

      Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
1012          1          0           0  ...        0          0       0

      Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
1012        0        0        0       0         1    0        0

[1 rows x 24 columns]
      movie_id                                          title release_date  \
1013      1014  Romy and Michele's High School Reunion (1997)  25-Apr-1997

      video_release_date                                           IMDb_url  \
1013                 NaN  http://us.imdb.com/M/title-exact?Romy%20and%20...

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
1013        0       0          0          0           0  ...        0

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
1013          0       0        0        0        0       0         0    0

      Western
1013        0

[1 rows x 24 columns]
     movie_id                    title release_date  video_release_date  \
503       504  Bonnie and Clyde (1967)  01-Jan-1967                 NaN

                                              IMDb_url  unknown  Action  \
503  http://us.imdb.com/M/title-exact?Bonnie%20and%...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
503          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
503        0        0        0       0         0    0        0

[1 rows x 24 columns]

In [55]:
import itertools
Final_recommend_movie = list(itertools.chain.from_iterable(movie_title_list))
print("The common movie in recom and user:",list(set(recom)&set(input_user_watched_movieid)))

The common movie in recom and user: []

In [56]:
Final_recommend_movie

['movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western',
 'movie_id',
 'title',
 'release_date',
 'video_release_date',
 'IMDb_url',
 'unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 ...]

In [57]:
def userbased(input_user,user_similarity,user_predictions,similar_user_count,thres):
    user_sim_table=pd.DataFrame(user_similarity)
    similar_input_user=user_sim_table[input_user].sort_values(ascending=True).head(5).index
    similar_user_input=list(similar_input_user)
    similar__user_movieid_list=[]
    for sim_user in similar_user_input:
        sim=list(ratings[ratings['user_id']==sim_user]['movie_id'])
        similar__user_movieid_list.append(sim)
    import itertools
    similar__user_movieid_single_list=list(itertools.chain.from_iterable(similar__user_movieid_list))
    unique_movieid_similar_user=set(similar__user_movieid_single_list)
    input_user_watched_movieid=list(ratings[ratings['user_id']==input_user]['movie_id'].values)
    recom=[]
    for per_id in unique_movieid_similar_user:
        if(per_id in input_user_watched_movieid):
            pass
        else:
            recom.append(per_id) 
    highest_rated=[]
    user_pred=pd.DataFrame(user_prediction)
    user_pred_Trans=user_pred.T
    input_user_pre=pd.DataFrame(user_pred_Trans[input_user])
    input_user_pred=input_user_pre.T
    for re in recom:
        value=input_user_pred[re].values
        if(value>=0.5):
                highest_rated.append(re)
        i_cols=["movie_id",  "title",  "release_date",  "video_release_date",  "IMDb_url","unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror",  "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"]
        items=pd.read_csv('ml-100k/u.item',sep="|", names=i_cols, encoding="latin-1")
        movie_title = []
        for movieid in highest_rated:
            mov = items[items['movie_id'] == movieid]  # Compare movie_id with movieid directly
            movie_title.append(mov)
        movie_title_list = []
        for m in movie_title: 
            print(m)
            mv =list(m)
            movie_title_list.append(mv)
        import itertools
        Final_recommend_movie = list(itertools.chain.from_iterable(movie_title_list))
        print("The common movie in recom and user:",list(set(recom)&set(input_user_watched_movieid)))
        return Final_recommend_movie

In [58]:
Recommended_movie=userbased(67,user_similarity,user_pred,5,1.5)

     movie_id              title release_date  video_release_date  \
513       514  Annie Hall (1977)  01-Jan-1977                 NaN

                                              IMDb_url  unknown  Action  \
513  http://us.imdb.com/M/title-exact?Annie%20Hall%...        0       0

     Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  \
513          0          0           0  ...        0          0       0

     Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
513        0        0        1       0         0    0        0

[1 rows x 24 columns]
The common movie in recom and user: []

In [59]:
len(Recommended_movie)

24