In [1]:
import numpy as np
import pandas as pd

In [2]:
r_cols=['user_id','movie_id','rating','unix_timestamp']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols,encoding='latin-1')

In [3]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [4]:
n_users=ratings.user_id.unique().shape[0]
n_items=ratings.movie_id.unique().shape[0]

In [5]:
print("The no of users:",n_users)
print("The no of items:",n_items)

The no of users: 943
The no of items: 1682

In [6]:
datama=ratings.pivot_table(index='user_id',columns='movie_id',values='rating')

In [7]:
datama

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data_matrix=datama.replace(np.nan,0)

In [9]:
data_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(data_matrix,metric='cosine')
item_similarity=pairwise_distances(data_matrix.T,metric='cosine')

In [11]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        # User-based prediction
        mean_user_rating = ratings.mean(axis=1)
        ratings_diff = ratings - mean_user_rating[:, np.newaxis]
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.abs(similarity).sum(axis=1)[:, np.newaxis]
    
    elif type == 'item':
        # Item-based prediction
        pred = ratings.dot(similarity.T) / np.abs(similarity).sum(axis=1)

    return pred

In [12]:
# Example Data
num_users = 943
num_items = 1682

# Random ratings matrix (users x items)
data_matrix = np.random.rand(num_users, num_items)

# User similarity matrix (users x users)
user_similarity = np.random.rand(num_users, num_users)

# Item similarity matrix (items x items)
item_similarity = np.random.rand(num_items, num_items)

# Predict user-based and item-based scores
user_prediction = predict(data_matrix, user_similarity, type='user')
item_prediction = predict(data_matrix, item_similarity, type='item')

print("User-based Prediction Shape:", user_prediction.shape)
print("Item-based Prediction Shape:", item_prediction.shape)

User-based Prediction Shape: (943, 1682)
Item-based Prediction Shape: (943, 1682)

In [13]:
user_prediction

array([[0.5093054 , 0.51656482, 0.51004424, ..., 0.51037272, 0.51575557,
        0.49949654],
       [0.49332106, 0.50414109, 0.49880479, ..., 0.50117794, 0.51524322,
        0.4903234 ],
       [0.48557411, 0.4807616 , 0.48674437, ..., 0.48971654, 0.49345678,
        0.47472177],
       ...,
       [0.49852001, 0.49661207, 0.49722955, ..., 0.51417562, 0.51910486,
        0.49906768],
       [0.50513956, 0.50593225, 0.51419083, ..., 0.5162136 , 0.51526451,
        0.49968585],
       [0.49443744, 0.48942164, 0.49401007, ..., 0.50607375, 0.50931472,
        0.47899451]])

In [14]:
input_item=34

In [15]:
item_sim_table=pd.DataFrame(item_similarity)

In [16]:
item_sim_table

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.492882,0.647152,0.504420,0.365762,0.373202,0.387094,0.662428,0.807442,0.823831,0.552466,...,0.549103,0.762162,0.651902,0.931739,0.446772,0.789065,0.962600,0.588547,0.772658,0.419530
1,0.147886,0.166567,0.382354,0.918477,0.749266,0.321255,0.171225,0.495321,0.839783,0.388586,...,0.716099,0.265463,0.308384,0.145757,0.923269,0.813495,0.154242,0.057820,0.377591,0.415487
2,0.363707,0.373322,0.824395,0.794252,0.164049,0.537058,0.814614,0.436724,0.368210,0.531392,...,0.106433,0.086580,0.067292,0.726070,0.549246,0.787122,0.970851,0.909135,0.474679,0.282665
3,0.947826,0.447763,0.206885,0.578974,0.140244,0.272724,0.999537,0.893523,0.304590,0.581663,...,0.424912,0.444281,0.449792,0.079964,0.699473,0.044496,0.293446,0.730770,0.824419,0.688552
4,0.677525,0.639740,0.014285,0.719285,0.366091,0.249043,0.725896,0.817431,0.988813,0.090607,...,0.089653,0.175301,0.285443,0.960603,0.684146,0.480244,0.842062,0.794594,0.954644,0.633442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.291836,0.711446,0.386031,0.396242,0.488434,0.567914,0.858680,0.199445,0.132243,0.860402,...,0.786980,0.065064,0.186401,0.638846,0.837375,0.097692,0.769130,0.324335,0.306968,0.422307
1678,0.099010,0.677219,0.732424,0.348727,0.955051,0.580300,0.236830,0.991825,0.136960,0.634815,...,0.732413,0.818740,0.912084,0.085871,0.880750,0.155915,0.829433,0.403277,0.762123,0.277894
1679,0.699790,0.722874,0.018168,0.367476,0.593844,0.900158,0.637981,0.132537,0.160961,0.160158,...,0.473105,0.547894,0.991263,0.354344,0.607266,0.521194,0.245166,0.934617,0.743539,0.251438
1680,0.268819,0.750680,0.097401,0.862595,0.309994,0.017716,0.440720,0.044813,0.320177,0.308695,...,0.673602,0.149253,0.482749,0.695272,0.041838,0.194454,0.596628,0.467120,0.896491,0.142429
1681,0.706868,0.359265,0.929143,0.366757,0.004393,0.927472,0.683055,0.404756,0.685637,0.327972,...,0.734781,0.894287,0.134207,0.876459,0.102815,0.011646,0.068817,0.035422,0.451863,0.368824

In [17]:
similar_input_item=item_sim_table[input_item].sort_values(ascending=True).head(5).index

In [18]:
similar_input_item

Int64Index([128, 972, 913, 496, 697], dtype='int64')

In [19]:
similar_item_input=list(similar_input_item)

In [20]:
similar_item_userid_list=[]
for sim_item in similar_item_input:
    sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
    similar_item_userid_list.append(sim)

In [21]:
similar_item_userid_list

[[22,
  158,
  280,
  95,
  201,
  221,
  1,
  346,
  70,
  393,
  130,
  399,
  297,
  363,
  385,
  267,
  466,
  429,
  60,
  279,
  268,
  394,
  276,
  435,
  291,
  487,
  522,
  13,
  62,
  654,
  621,
  746,
  758,
  633,
  653,
  804,
  833,
  757,
  715,
  303,
  301,
  551,
  655,
  838,
  643,
  880,
  868,
  638,
  738,
  497,
  682,
  886,
  806,
  887,
  198,
  864,
  889,
  921,
  727,
  896,
  823,
  771,
  851,
  87,
  805],
 [222,
  184,
  59,
  151,
  378,
  345,
  344,
  90,
  18,
  387,
  504,
  416,
  407,
  506,
  72,
  201,
  661,
  804,
  429,
  454,
  763,
  864,
  766,
  537,
  655,
  934,
  405,
  918],
 [13, 655],
 [250,
  124,
  18,
  138,
  321,
  293,
  59,
  195,
  301,
  75,
  326,
  189,
  274,
  298,
  276,
  299,
  10,
  114,
  291,
  51,
  312,
  275,
  130,
  389,
  175,
  406,
  221,
  360,
  339,
  42,
  379,
  115,
  253,
  94,
  125,
  95,
  380,
  7,
  450,
  16,
  295,
  263,
  70,
  58,
  458,
  43,
  416,
  313,
  151,
  215,
  465,
  399,
  236,
  290,
  378,
  48,
  478,
  474,
  385,
  409,
  556,
  346,
  538,
  542,
  454,
  235,
  553,
  148,
  533,
  571,
  85,
  495,
  601,
  618,
  567,
  387,
  588,
  488,
  200,
  161,
  394,
  586,
  280,
  398,
  536,
  505,
  314,
  57,
  234,
  90,
  44,
  269,
  308,
  429,
  437,
  622,
  707,
  453,
  407,
  716,
  373,
  660,
  87,
  666,
  560,
  748,
  704,
  747,
  650,
  342,
  776,
  738,
  641,
  214,
  796,
  184,
  524,
  452,
  230,
  20,
  605,
  97,
  764,
  527,
  472,
  532,
  82,
  354,
  659,
  815,
  778,
  694,
  393,
  840,
  262,
  535,
  690,
  836,
  749,
  710,
  741,
  640,
  766,
  711,
  780,
  630,
  383,
  758,
  790,
  435,
  128,
  911,
  878,
  928,
  311,
  899,
  539,
  254,
  882,
  498,
  806,
  864,
  643,
  194,
  912,
  503,
  216,
  154,
  506,
  343,
  271,
  561,
  892,
  734,
  334,
  653,
  60,
  647,
  382,
  875,
  645,
  496,
  642,
  942,
  786,
  848,
  577,
  566,
  886,
  6,
  867,
  924,
  617,
  868,
  862,
  521,
  847,
  870,
  661,
  664,
  896,
  371,
  887,
  785,
  593,
  897,
  804,
  344,
  64,
  883,
  771,
  908,
  417,
  907,
  363,
  932,
  537,
  846,
  648,
  850,
  330,
  807,
  698,
  426,
  929,
  665,
  731,
  890,
  479,
  654,
  691],
 [216,
  119,
  172,
  62,
  387,
  303,
  276,
  318,
  453,
  10,
  314,
  537,
  280,
  435,
  618,
  244,
  474,
  405,
  682,
  399,
  271,
  437,
  627,
  85,
  715,
  886,
  456,
  738,
  880,
  887,
  870,
  693,
  846,
  916,
  588,
  201,
  269,
  429,
  907,
  709]]

In [22]:
import itertools
similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))

In [23]:
len(similar_item_userid_single_list)

366

In [24]:
unique_userid_similar_item=set(similar_item_userid_single_list)

In [25]:
len(unique_userid_similar_item)

282

In [26]:
input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)

In [27]:
input_item_watched_userid

[286, 276, 94, 184, 1, 551, 297]

In [28]:
recom=[]
for per_id in unique_userid_similar_item:
    if(per_id in input_item_watched_userid):
        pass
    else:
        recom.append(per_id)

In [29]:
len(recom)

276

In [30]:
sorted(recom)

[6,
 7,
 10,
 13,
 16,
 18,
 20,
 22,
 42,
 43,
 44,
 48,
 51,
 57,
 58,
 59,
 60,
 62,
 64,
 70,
 72,
 75,
 82,
 85,
 87,
 90,
 95,
 97,
 114,
 115,
 119,
 124,
 125,
 128,
 130,
 138,
 148,
 151,
 154,
 158,
 161,
 172,
 175,
 189,
 194,
 195,
 198,
 200,
 201,
 214,
 215,
 216,
 221,
 222,
 230,
 234,
 235,
 236,
 244,
 250,
 253,
 254,
 262,
 263,
 267,
 268,
 269,
 271,
 274,
 275,
 279,
 280,
 290,
 291,
 293,
 295,
 298,
 299,
 301,
 303,
 308,
 311,
 312,
 313,
 314,
 318,
 321,
 326,
 330,
 334,
 339,
 342,
 343,
 344,
 345,
 346,
 354,
 360,
 363,
 371,
 373,
 378,
 379,
 380,
 382,
 383,
 385,
 387,
 389,
 393,
 394,
 398,
 399,
 405,
 406,
 407,
 409,
 416,
 417,
 426,
 429,
 435,
 437,
 450,
 452,
 453,
 454,
 456,
 458,
 465,
 466,
 472,
 474,
 478,
 479,
 487,
 488,
 495,
 496,
 497,
 498,
 503,
 504,
 505,
 506,
 521,
 522,
 524,
 527,
 532,
 533,
 535,
 536,
 537,
 538,
 539,
 542,
 553,
 556,
 560,
 561,
 566,
 567,
 571,
 577,
 586,
 588,
 593,
 601,
 605,
 617,
 618,
 621,
 622,
 627,
 630,
 633,
 638,
 640,
 641,
 642,
 643,
 645,
 647,
 648,
 650,
 653,
 654,
 655,
 659,
 660,
 661,
 664,
 665,
 666,
 682,
 690,
 691,
 693,
 694,
 698,
 704,
 707,
 709,
 710,
 711,
 715,
 716,
 727,
 731,
 734,
 738,
 741,
 746,
 747,
 748,
 749,
 757,
 758,
 763,
 764,
 766,
 771,
 776,
 778,
 780,
 785,
 786,
 790,
 796,
 804,
 805,
 806,
 807,
 815,
 823,
 833,
 836,
 838,
 840,
 846,
 847,
 848,
 850,
 851,
 862,
 864,
 867,
 868,
 870,
 875,
 878,
 880,
 882,
 883,
 886,
 887,
 889,
 890,
 892,
 896,
 897,
 899,
 907,
 908,
 911,
 912,
 916,
 918,
 921,
 924,
 928,
 929,
 932,
 934,
 942]

In [31]:
sorted(unique_userid_similar_item)

[1,
 6,
 7,
 10,
 13,
 16,
 18,
 20,
 22,
 42,
 43,
 44,
 48,
 51,
 57,
 58,
 59,
 60,
 62,
 64,
 70,
 72,
 75,
 82,
 85,
 87,
 90,
 94,
 95,
 97,
 114,
 115,
 119,
 124,
 125,
 128,
 130,
 138,
 148,
 151,
 154,
 158,
 161,
 172,
 175,
 184,
 189,
 194,
 195,
 198,
 200,
 201,
 214,
 215,
 216,
 221,
 222,
 230,
 234,
 235,
 236,
 244,
 250,
 253,
 254,
 262,
 263,
 267,
 268,
 269,
 271,
 274,
 275,
 276,
 279,
 280,
 290,
 291,
 293,
 295,
 297,
 298,
 299,
 301,
 303,
 308,
 311,
 312,
 313,
 314,
 318,
 321,
 326,
 330,
 334,
 339,
 342,
 343,
 344,
 345,
 346,
 354,
 360,
 363,
 371,
 373,
 378,
 379,
 380,
 382,
 383,
 385,
 387,
 389,
 393,
 394,
 398,
 399,
 405,
 406,
 407,
 409,
 416,
 417,
 426,
 429,
 435,
 437,
 450,
 452,
 453,
 454,
 456,
 458,
 465,
 466,
 472,
 474,
 478,
 479,
 487,
 488,
 495,
 496,
 497,
 498,
 503,
 504,
 505,
 506,
 521,
 522,
 524,
 527,
 532,
 533,
 535,
 536,
 537,
 538,
 539,
 542,
 551,
 553,
 556,
 560,
 561,
 566,
 567,
 571,
 577,
 586,
 588,
 593,
 601,
 605,
 617,
 618,
 621,
 622,
 627,
 630,
 633,
 638,
 640,
 641,
 642,
 643,
 645,
 647,
 648,
 650,
 653,
 654,
 655,
 659,
 660,
 661,
 664,
 665,
 666,
 682,
 690,
 691,
 693,
 694,
 698,
 704,
 707,
 709,
 710,
 711,
 715,
 716,
 727,
 731,
 734,
 738,
 741,
 746,
 747,
 748,
 749,
 757,
 758,
 763,
 764,
 766,
 771,
 776,
 778,
 780,
 785,
 786,
 790,
 796,
 804,
 805,
 806,
 807,
 815,
 823,
 833,
 836,
 838,
 840,
 846,
 847,
 848,
 850,
 851,
 862,
 864,
 867,
 868,
 870,
 875,
 878,
 880,
 882,
 883,
 886,
 887,
 889,
 890,
 892,
 896,
 897,
 899,
 907,
 908,
 911,
 912,
 916,
 918,
 921,
 924,
 928,
 929,
 932,
 934,
 942]

In [32]:
sorted(input_item_watched_userid)

[1, 94, 184, 276, 286, 297, 551]

In [33]:
list(set(unique_userid_similar_item)&set(input_item_watched_userid))

[1, 551, 297, 276, 184, 94]

In [34]:
item_pred=pd.DataFrame(item_prediction)

In [35]:
item_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.511747,0.509111,0.509237,0.518948,0.508404,0.513978,0.506649,0.512955,0.504660,0.514932,...,0.509944,0.510949,0.513833,0.513662,0.510911,0.513547,0.516281,0.519695,0.509179,0.515103
1,0.507204,0.502648,0.493342,0.501761,0.497292,0.490018,0.501017,0.503068,0.503742,0.499996,...,0.500186,0.493595,0.496739,0.501601,0.503469,0.498444,0.503317,0.498967,0.495566,0.493649
2,0.488229,0.489305,0.492482,0.493354,0.484518,0.486843,0.492889,0.483018,0.492047,0.483348,...,0.491889,0.495015,0.493546,0.494473,0.481556,0.490258,0.488484,0.484972,0.487629,0.488114
3,0.513488,0.515053,0.510894,0.514376,0.511288,0.513321,0.509215,0.512464,0.509057,0.507466,...,0.515359,0.511476,0.513240,0.518389,0.508917,0.519424,0.512036,0.506096,0.514222,0.503942
4,0.502469,0.512278,0.513678,0.510202,0.508043,0.511593,0.510151,0.513953,0.512809,0.513383,...,0.508218,0.511147,0.508450,0.510931,0.516237,0.514189,0.514730,0.516009,0.508451,0.514639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.494306,0.487582,0.496819,0.489903,0.489717,0.485990,0.487539,0.491529,0.488197,0.487122,...,0.500759,0.488933,0.489628,0.492416,0.493210,0.496014,0.489987,0.480154,0.491419,0.501515
939,0.497104,0.500294,0.501180,0.503327,0.491779,0.511315,0.500271,0.501492,0.497112,0.496236,...,0.500459,0.502992,0.501541,0.500488,0.501124,0.510716,0.504406,0.502345,0.509003,0.497003
940,0.505166,0.506341,0.510243,0.500779,0.502724,0.502096,0.512447,0.514639,0.509014,0.507811,...,0.502544,0.505008,0.500746,0.505239,0.508010,0.502813,0.505219,0.512505,0.509678,0.510073
941,0.520232,0.506078,0.506743,0.520098,0.515617,0.510467,0.513631,0.507876,0.515282,0.511438,...,0.507221,0.515106,0.516069,0.511995,0.515087,0.512386,0.513989,0.510782,0.519204,0.511235
942,0.500679,0.498704,0.505500,0.493482,0.497081,0.503643,0.495830,0.496451,0.493751,0.490739,...,0.494487,0.492811,0.493997,0.498177,0.496889,0.495503,0.490513,0.494094,0.496337,0.495262

In [36]:
item_pred[input_item]

0      0.505177
1      0.497133
2      0.492431
3      0.508794
4      0.520327
         ...
938    0.491515
939    0.505283
940    0.514686
941    0.507130
942    0.493370
Name: 34, Length: 943, dtype: float64

In [37]:
highest_rated=[]
input_item_pre=pd.DataFrame(item_pred[input_item])
input_item_pred=input_item_pre.T
for re in recom:
    value=input_item_pred[re].values
    if(value>=0.517):
        highest_rated.append(re)

In [38]:
len(highest_rated)

5

In [39]:
list(set(recom) & set(input_item_watched_userid))

[]

In [40]:
def itembased(input_item,item_similarity,item_predictions,similar_item_count,thres):
    item_sim_table=pd.DataFrame(item_similarity)
    similar_input_item=item_sim_table[input_item].sort_values(ascending=True).head(similar_item_count).index
    similar_item_input=list(similar_input_item)
    similar_item_userid_list=[]
    for sim_item in similar_item_input:
        sim=list(ratings[ratings['movie_id']==sim_item]['user_id'])
        similar_item_userid_list.append(sim)
    import itertools
    similar_item_userid_single_list=list(itertools.chain.from_iterable(similar_item_userid_list))
    unique_userid_similar_item=set(similar_item_userid_single_list)
    input_item_watched_userid=list(ratings[ratings['movie_id']==input_item]['user_id'].values)
    recom=[]
    for per_id in unique_userid_similar_item:
        if(per_id in input_item_watched_userid):
            pass
        else:
            recom.append(per_id) 
    highest_rated=[]
    user_pred=pd.DataFrame(item_prediction)
    input_item_pre=pd.DataFrame(user_pred[input_item])
    input_item_pred=input_item_pre.T
    for re in recom:
        value=input_item_pred[re].values
        if(value>=thres):
            highest_rated.append(re)
    highest_rated
    return highest_rated

In [41]:
Recommended_user = itembased(5, item_similarity, item_pred, 5, 0.517)

In [42]:
len(Recommended_user)

3

In [43]:
Recommended_user

[588, 315, 927]